<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Company>Conan Server Control</Company>
    <Product>Conan Server Control</Product>
    <Authors>Conan Server Control</Authors>
    <Copyright>Copyright (c) Conan Server Control</Copyright>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
