import json, ast, re
S = r"C:\Users\vkkha\AppData\Local\Temp\claude\E--github-gameee\38dc645d-3cc9-4427-a274-ffaba69e9f7f\scratchpad"
P = {
"The buildings of these Giant-king Vassals are built in the same style of Giant-king architecture, but at a scale more appropriate to humans. Yet look closely at the make and compare to the bones of the Giant-king civilization scattered throughout the Exiled Lands, and you will see where the Vassals' imitation falls short. While they did their best to emulate the look, they could not mimic the methods the Giant-kings used to build their works.":
"Các công trình của Chư Hầu Vua Khổng Lồ được xây theo cùng phong cách kiến trúc Vua Khổng Lồ, nhưng ở tỉ lệ hợp với con người hơn. Thế nhưng hãy nhìn kỹ cách xây và so với tàn tích của nền văn minh Vua Khổng Lồ rải rác khắp Vùng Đất Lưu Đày, bạn sẽ thấy sự bắt chước của các Chư Hầu còn kém ở đâu. Dù họ cố hết sức mô phỏng vẻ ngoài, họ không thể bắt chước phương pháp mà các Vua Khổng Lồ dùng để dựng nên công trình.",
"<LoreItalics>\"He halted suddenly, posed like a statue at the foot of the stair, staring at the paintings which frescoed the walls, half visible in the dim light which filtered down from above. The art was unmistakably Pelishti; he had seen frescoes of identical characteristics on the walls of Asgalun.\"</> - Jewels of Gwahlur":
"<LoreItalics>\"Hắn đột ngột dừng lại, đứng như tượng dưới chân cầu thang, nhìn chằm chằm những bức bích họa trên tường, lờ mờ hiện ra trong ánh sáng yếu ớt lọt xuống từ phía trên. Lối vẽ không thể lẫn vào đâu là của Pelishti; hắn đã thấy những bức bích họa y hệt trên tường thành Asgalun.\"</> - Jewels of Gwahlur",
"SHEMCITY": "Dù Shem có ít thành phố, những thành phố họ có lại là trung tâm quốc tế nổi bật. Các đoàn lữ hành chở hàng tới Turan và Khitai dừng chân trước tiên ở những thành phố Shem như Asgalun và Pelishtia, còn các thành phố ven biển của Shem tự hào có những cảng biển nhộn nhịp, nơi người Shem được chọn trước kho báu do thương nhân và hải tặc từ Zingara, Argos và Stygia mang tới. Là trung tâm thương mại, các thành phố Shem đã hình thành một nền văn hóa say mê nghệ thuật và cái đẹp - một sở thích bị kẻ đố kỵ và ngu dốt bóp méo thành tiếng tham lam.",
"Sloped rooves are practical in sandstorms as the loose debris simply runs from the roof rather than accumulating.":"Mái dốc rất thực dụng trong bão cát vì mảnh vụn trôi khỏi mái chứ không đọng lại.",
"This low fence is not designed to keep enemies out, but rather to provide defensive archers with a measure of cover between shots.":"Hàng rào thấp này không nhằm chặn kẻ thù mà để cung thủ phòng thủ có chỗ nấp giữa các phát bắn.",
"It is said that nobody is truly home until they have a roof over their head.":"Người ta nói chưa ai thật sự có nhà cho tới khi có mái che trên đầu.",
"This beautiful ceiling does more than just keep the sandstorms and bat demons away.":"Trần nhà đẹp đẽ này làm được nhiều hơn là chỉ chặn bão cát và quỷ dơi.",
"When moving huge wheeled wagons filled to the brim with rare resources, luxury goods or even slaves, ramps are much preferred over stairs, for self-evident reasons.":"Khi di chuyển những cỗ xe bánh lớn chất đầy tài nguyên quý, hàng xa xỉ hay thậm chí nô lệ, đường dốc được ưa hơn cầu thang hẳn, vì những lý do hiển nhiên.",
"Pillars offer stability to tall structures, allowing height to become a significant factor in building. Be aware, however, that pillars also offer a unique weak point for enemies to attack.":"Cột giúp công trình cao vững chắc, khiến chiều cao trở thành yếu tố quan trọng khi xây dựng. Tuy nhiên hãy nhớ cột cũng là điểm yếu đặc biệt để kẻ thù tấn công.",
"These large doors are designed to allow access for large groups of people in and out of safe areas. Raiders and bandits make walls a must have in the Exiled Lands and the protection afforded by gates such as these should not be taken for granted.":"Những cánh cửa lớn này được thiết kế để nhóm đông người ra vào khu an toàn. Bọn cướp khiến tường thành là thứ bắt buộc ở Vùng Đất Lưu Đày, và đừng coi nhẹ sự bảo vệ mà những cánh cổng như thế mang lại.",
"One of the strongest doors that can be crafted, the heavy door offers protection against everything but the most powerful of enemy tricks.":"Một trong những cánh cửa chắc nhất có thể chế tạo, cửa nặng bảo vệ trước mọi thứ, trừ những mánh khóe mạnh nhất của kẻ thù.",
"Raging hordes have been kept at bay by such doors and with a simple locking mechanism they become proof against incursions into structures.":"Những đoàn quân cuồng nộ đã bị chặn lại bởi những cánh cửa như thế, và với một cơ cấu khóa đơn giản chúng ngăn được mọi cuộc xâm nhập.",
"Walls are a comfort for the timid, a strength to the strategist and a trap for the unwary.":"Tường là niềm an ủi của kẻ nhút nhát, sức mạnh của nhà chiến lược và cạm bẫy cho kẻ khinh suất.",
"A barrier against the savage world, walls can be built as high as the stability of the foundations will allow. The strength of the materials used in their construction will determine how long they stay up.":"Là rào chắn trước thế giới man rợ, tường có thể xây cao tới mức nền móng chịu được. Độ chắc của vật liệu sẽ quyết định chúng đứng vững bao lâu.",
"The strength of walls during a siege is determined by two things - the strength of building itself and the ability of defenders to cleanly shoot enemies that are attacking.":"Sức mạnh của tường khi bị vây hãm phụ thuộc hai điều - độ chắc của chính công trình và khả năng người phòng thủ bắn trúng kẻ địch đang tấn công.",
"These crenelated walls are a common design, effective at giving archers a clear space for firing on enemies as well as providing a niche for placing siege cauldrons and other defensive mechanisms.":"Tường răng cưa là thiết kế phổ biến, giúp cung thủ có khoảng trống để bắn kẻ địch, đồng thời có hốc để đặt vạc công thành và các cơ cấu phòng thủ khác.",
"Just remember to add a door.":"Chỉ cần nhớ làm thêm cửa.",
"The best battle, they say, is the one you never have to fight. With formidable enough gates, the enemies will think twice about attacking any fortress. Not simply because the scale of the gates has them concerned about getting inside, but because large gates imply large inhabitants and armies get nervous when they think they might be outnumbered.":"Người ta nói trận chiến tốt nhất là trận không bao giờ phải đánh. Với những cánh cổng đủ đáng gờm, kẻ thù sẽ nghĩ kỹ trước khi tấn công bất kỳ pháo đài nào. Không chỉ vì cổng lớn khiến chúng lo không vào được, mà vì cổng lớn ngụ ý bên trong đông người, và quân đội luôn chột dạ khi nghĩ mình có thể bị áp đảo về số lượng.",
"Foundations should be the starting point for almost any structure. They provide stability to anything built atop them and prevent the growth of plants beneath them.":"Nền móng nên là điểm khởi đầu của gần như mọi công trình. Chúng giúp mọi thứ xây trên đó vững chắc và ngăn cây cỏ mọc bên dưới.",
"Placing a foundation is a significant act in the Exiled Lands. Once a foundation is placed by a clan or individual, that land is considered their territory. Nobody else may build in the immediate area, unless the foundation is destroyed.":"Đặt nền móng là hành động quan trọng ở Vùng Đất Lưu Đày. Khi một clan hay cá nhân đã đặt nền móng, vùng đất đó được coi là lãnh thổ của họ. Không ai khác được xây trong khu vực đó, trừ khi nền móng bị phá hủy.",
"Any warrior with even a little battle hardening will agree that the safest ground to defend is the high ground. And if there is no high ground to defend, make it yourself.":"Bất kỳ chiến binh nào từng trải chút ít trận mạc đều đồng ý rằng nơi an toàn nhất để phòng thủ là chỗ cao. Và nếu không có chỗ cao để giữ, hãy tự tạo ra nó.",
"Stairs are a necessity once buildings grow beyond a certain size. They provide points of natural defence and easy access to higher floors and rooftops (which make excellent archery platforms). Their only weakness is the material upon which they are built - if the high ground is brought crashing down then it no longer serves a tactical purpose.":"Cầu thang là thứ cần thiết khi công trình vượt quá một kích thước nhất định. Chúng tạo điểm phòng thủ tự nhiên và lối lên dễ dàng tới tầng trên và mái nhà (nơi làm bệ bắn cung tuyệt vời). Điểm yếu duy nhất là vật liệu xây chúng - nếu chỗ cao bị đánh sập thì nó không còn giá trị chiến thuật.",
"Every structure that has ever fallen to an enemy has been breached somewhere. And the breach point, more often than not, is the door.":"Mọi công trình từng thất thủ đều bị chọc thủng ở đâu đó. Và chỗ bị chọc thủng, thường hơn cả, là cánh cửa.",
"A door is only as strong as the place where it is anchored and many a would-be warlord has come to grief when their solidly constructed door was torn off at the anchor point.":"Cánh cửa chỉ chắc bằng chỗ nó được neo vào, và không ít kẻ muốn làm lãnh chúa đã khốn đốn khi cánh cửa chắc chắn của họ bị giật bung ở chỗ neo.",
"The difference between a king and a pauper might just be the entrance to his kingdom.":"Khác biệt giữa vua và kẻ ăn mày có khi chỉ là lối vào vương quốc của hắn.",
"Weapons barely chip it and even explosive powder is not enough to weaken it in a single blow. Siege weapons or divine intervention are really the only way to bring down walls this strong.":"Vũ khí hầu như không làm sứt mẻ nó, và ngay cả bột nổ cũng không đủ làm suy yếu nó chỉ trong một đòn. Vũ khí công thành hay sự can thiệp của thần linh thật sự là cách duy nhất để hạ những bức tường chắc chắn thế này.",
"LIVING1": "Những lữ khách mệt mỏi sau khi dựng trại qua đêm thường nhìn vào bóng tối. Để mắt và đầu óc nghỉ ngơi bằng cách nhìn vô định về phía trước.",
"What is not common is to stare into the shadows and realize that they are staring back at you.":"Điều không thường gặp là nhìn vào bóng tối và nhận ra chúng đang nhìn lại bạn.",
"LIVING3": "Có những câu chuyện về một tộc người kỳ lạ từng sống sâu trong rừng rậm Vùng Đất Lưu Đày. Thận trọng và lén lút, họ thích rình rập từ xa. Khi bị bắt, họ chống trả hung dữ như thú bị dồn vào đường cùng. Những ai thoát được đều cảnh báo rằng thấy một trong những bóng tối sống ấy nghĩa là sắp có một cuộc đột kích.",
"This bow will be able to bring down both human and non-human foes, but it relies heavily on the skill of the user.":"Cây cung này hạ được cả kẻ thù là người lẫn không phải người, nhưng phụ thuộc nhiều vào tay nghề người dùng.",
"Light armor provides the most flexibility and range of moment in combat, but at the cost of significant protection in battle.":"Giáp nhẹ cho sự linh hoạt và biên độ cử động lớn nhất khi chiến đấu, nhưng phải đánh đổi khá nhiều khả năng bảo vệ.",
"At times used for ceremonial purposes, these punching daggers may also be used to slice and stab opponents in close combat.":"Đôi khi dùng cho nghi lễ, những dao găm đấm này cũng có thể dùng để chém và đâm đối thủ khi cận chiến.",
"Great swords are faster than many other two-handed weapons, and their great reach makes them ideal for fending off groups of opponents.":"Đại kiếm nhanh hơn nhiều vũ khí hai tay khác, và tầm với dài khiến chúng lý tưởng để chống lại nhóm kẻ địch.",
"Because they are smaller and weigh less than other weapons, short swords are also faster to use and consume less stamina than their larger counterparts.":"Vì nhỏ và nhẹ hơn các vũ khí khác, đoản kiếm cũng dùng nhanh hơn và tốn ít thể lực hơn loại lớn.",
"This shield is designed for attack as much as defence. A well placed strike with the shield can stagger an enemy and leave them open to attacks from a weapon in the main hand.":"Chiếc khiên này được thiết kế để tấn công cũng như phòng thủ. Một cú đập khiên đúng chỗ có thể làm kẻ địch choáng và mở sơ hở cho vũ khí ở tay chính.",
"Capable of cutting and dicing, slashing and slaying, daggers are for those who like to get in close and wreak havoc. Then move to a safe distance while their enemies bleed out.":"Cắt, thái, chém và giết, dao găm dành cho những ai thích áp sát và gây hỗn loạn. Rồi lùi ra khoảng cách an toàn trong khi kẻ thù chảy máu tới chết.",
"Some warpaints are designed to be prayers to the gods, infusing the wearer with their strength and skill. Some warpaints are merely decorative, worn to show allegiance or affiliation with a clan.":"Có loại sơn chiến được vẽ như lời cầu nguyện thần linh, truyền sức mạnh và kỹ năng cho người mang. Có loại chỉ để trang trí, thể hiện lòng trung thành hay sự gắn bó với một clan.",
"Mauls and warhammers are slow to swing and leave their user vulnerable to counterattack, but when they connect they are brutally effective. Armored foes are particularly vulnerable to these massive blunt weapons which break bones, shatter skulls and crush spines.":"Búa tạ và búa chiến vung chậm và khiến người dùng dễ bị phản đòn, nhưng khi trúng đích thì cực kỳ tàn bạo. Kẻ địch mặc giáp đặc biệt dễ tổn thương trước những vũ khí cùn đồ sộ này, chúng bẻ xương, vỡ sọ và nghiền nát cột sống.",
"Offering significantly more protection than light armor, this medium armor incorporates a balance of protection and agility. This middle of the road approach brings compromises of its own because this armor is neither as strong as heavy armor, nor as flexible as light armor.":"Bảo vệ tốt hơn hẳn giáp nhẹ, giáp vừa này cân bằng giữa phòng thủ và linh hoạt. Cách tiếp cận trung dung này có đánh đổi riêng, vì nó không chắc bằng giáp nặng cũng không linh hoạt bằng giáp nhẹ.",
"Longsword has become a catch-all phrase for the mongrel swords of a thousand different makes that don't align easily with one simple classification.":"Trường kiếm đã trở thành từ gọi chung cho những thanh kiếm lai tạp của cả nghìn kiểu chế tác khác nhau, không dễ xếp vào một loại đơn giản.",
"The only description of a longsword that seems to be agreed upon is that they are double-bladed and straight. Beyond that, they vary wildly from grooved blades to smooth blades, long hilts to short hilts, and one-handed and two-handed variations.":"Điểm duy nhất người ta đồng ý về trường kiếm là hai lưỡi và thẳng. Ngoài ra chúng khác nhau rất nhiều, từ lưỡi có rãnh đến lưỡi trơn, chuôi dài đến chuôi ngắn, loại một tay lẫn hai tay.",
"CITYLIFE": "Sống ở thành phố là hòa mình vào văn minh và văn hóa - nhưng cũng có nghĩa là đông người sống sát nhau, chắc chắn sẽ sinh chuyện.",
"The pinnacle of protection, steel armor is a solid wall of defense against any type of attack, but the extreme weight requirements mean that the wearer must sacrifice mobility.":"Đỉnh cao của sự bảo vệ, giáp thép là bức tường phòng thủ vững chắc trước mọi loại tấn công, nhưng trọng lượng cực lớn khiến người mặc phải hy sinh sự cơ động.",
}
NORM = [  # paragraph variants -> canonical key
 (re.compile(r"^Though Shem has few cities"), "SHEMCITY"),
 (re.compile(r"^It is common for weary travellers"), "LIVING1"),
 (re.compile(r"^There are stories of a strange people"), "LIVING3"),
 (re.compile(r"^To live in a city is to immerse yourself"), "CITYLIFE"),
]
GUARD = {
 "weapons such as these": "Ở những thành phố lớn của Shem như Asgalun, Pelishtia và Kyros, vũ khí như thế này là trang bị tiêu chuẩn của vệ binh thành. Giáp tấm nặng đủ bảo vệ khi tình hình leo thang và cũng giúp cả dân thường lẫn tội phạm dễ nhận ra họ giữa đám đông.",
 "uniforms such as these": "Ở những thành phố lớn của Shem như Asgalun, Pelishtia, Kyros và Sukhmet, đồng phục như thế này là trang bị tiêu chuẩn của vệ binh thành. Giáp tấm nặng đủ bảo vệ khi tình hình leo thang và cũng giúp cả dân thường lẫn tội phạm dễ nhận ra họ giữa đám đông.",
}
WHOLE = {
580:"Với tầm với vượt trội, giáo là vũ khí phổ biến trên chiến trường Hyboria. Cách dùng hiệu quả nhất là từ phía sau hàng chiến tuyến, đâm vào khe hở của tường khiên.\r\nNgười Lemuria là một dân tộc hải đảo, sống trên chuỗi đảo ngoài khơi bờ đông lục địa Thuria - cho tới khi vương quốc của họ chìm xuống biển. Câu chuyện của họ rẽ sang hướng tàn khốc khi họ đặt chân lên bờ biển phía đông - và lập tức bị tộc người sống ở đó bắt làm nô lệ.\r\nVì sao cổ vật Lemuria lại ở đây vẫn là bí ẩn. Giống như chính Vùng Đất Lưu Đày.",
581:"Làm từ đá thô, đài phun nước này giữ được một ít nước.\n\nNước là yếu tố thiết yếu để sinh tồn, càng đúng gấp đôi ở môi trường sa mạc của Vùng Đất Lưu Đày. Bất kỳ khu định cư lâu dài nào gần nguồn nước rồi cũng sẽ bị kẻ khác tranh giành vì thứ tài nguyên nuôi sự sống này.\n\nSự tiện lợi của giếng cho phép xây dựng ở những nơi lẽ ra không thể sống được. Giếng đầy nước dần theo thời gian và có thể dùng để giải khát, đổ đầy túi nước và làm hàng chục việc khác cần đến nước.",
582:"Tê giác đã thuần hóa mang lại lợi thế lớn cho người cưỡi khắp Vùng Đất Lưu Đày. Người cưỡi thường ở đủ cao để nhìn xa hơn, hiểu rõ hơn môi trường xung quanh. Nhờ tầm nhìn đó, chiến binh cưỡi tê giác có thể nhanh chóng đổi hướng và điều khiển thú cưỡi, tăng khả năng phòng thủ hay tấn công.\n\nThường chỉ riêng việc một con tê giác tiến tới đã đủ làm hầu hết thú vật và những clan chiến binh nhỏ bỏ chạy, vì chẳng cần trải nghiệm tận mắt cũng thấy những con thú này có thể tàn phá khủng khiếp trên chiến trường.",
583:"<LoreItalics>Tascela ngả người trên ngai ngà. Những bát đồng đựng hương cuộn khói quanh nàng; những làn khói mỏng quấn quanh tứ chi trần trụi của nàng như những ngón tay vuốt ve.</> - Red Nails\n\nChiếc vạc khiêm tốn vốn được đầu bếp dùng để nấu ăn. Tuy nhiên, nhờ sự đa dụng, nó cũng được các nhà giả kim và phù thủy săn lùng để pha chế những thí nghiệm kỳ lạ.\n\nChất xúc tác luyện kim như Thép Lửa chỉ có thể được tạo ra bởi nhà giả kim biết đúng công thức phối trộn nguyên liệu.\n\nLoại vạc đặc biệt này lần đầu được dùng phổ biến ở Vendhya.",
584:"Điệu múa dao Shem là màn trình diễn kỹ năng truyền thống - động tác có thể gợi cảm, nhưng vũ công phải có sự khéo léo, sức mạnh và lòng tin vào bản thân lẫn bạn diễn để múa mà không làm ai bị thương. Thường biểu diễn trong lễ hội hay dịp ăn mừng, các điệu múa này thường dâng lên các vị thần sinh sản của Shem như Ishtar, Pteor và Derketo.\n\nCắt, thái, chém và giết, dao găm dành cho những ai thích áp sát và gây hỗn loạn. Rồi lùi ra khoảng cách an toàn trong khi kẻ thù chảy máu tới chết.",
585:"<LoreItalics>'Họ chẳng có hy vọng nào ở đời này lẫn đời sau,' Conan đáp. 'Thần của họ là Crom và giống nòi u tối của hắn, cai trị một nơi không mặt trời mù sương vĩnh cửu, đó là thế giới của người chết. Mitra! Lối sống của người Aesir hợp ý ta hơn.'</> - The Phoenix on the Sword\r\n\r\nNgười Cimmeria là một dân tộc khỏe mạnh, và họ cũng ăn uống thịnh soạn khi có điều kiện. Nhưng người Cimmeria cũng là một dân tộc khắc khổ, và những thứ như gia vị và hương vị hiếm khi chạm tới lưỡi họ. Món ăn đạm bạc như vậy càng khiến việc có nồi niêu nấu được nhiều mà không bị cháy trở nên quan trọng.",
591:"Dù người Tây Shem đã bỏ lối sống du mục của họ hàng sa mạc, họ vẫn giữ chặt tri thức và truyền thống chăn nuôi. Người Shem nổi tiếng với những đàn gia súc chăn thả và tài chăm sóc chúng - cừu và dê là phổ biến nhất, nhưng người Shem vùng đồng cỏ còn học được bí quyết thuần hóa những con tê giác hùng mạnh gặm cỏ trên đồi và đồng cỏ của họ.\n\nNhững con thú này phục vụ trong đơn vị kỵ binh của nhiều thành phố Shem. Họa tiết tê giác xuất hiện khắp nghệ thuật và kiến trúc Shem là cách họ bày tỏ lòng biết ơn sự che chở của những con thú đáng gờm này.",
592:"<LoreItalics>Tức là họ đã học được cách rèn thô sơ đồng và thiếc, những thứ hiếm hoi ở xứ họ; để có thiếc, họ đột kích vào núi Zingara, hoặc đổi da thú, răng cá voi, ngà hải mã và vài thứ ít ỏi mà dân man rợ có thể đem trao đổi.</>- The Hyborian Age\n\nNghề rèn là nghề phổ biến và được dùng nhiều ở các vương quốc Hyboria. Ở các thành phố và thị trấn lớn, thợ rèn buộc phải gia nhập phường hội để được bảo vệ phần nào về chính trị, đồng thời tuân theo những tiêu chuẩn khắt khe về tay nghề và dụng cụ.\n\nChiếc bàn này có nhiều dụng cụ thợ rèn cần, nhưng ở Vùng Đất Lưu Đày thì chẳng có tiêu chuẩn nào để tuân theo cả.",
604:"<LoreItalics>'Nằm đây.' Hắn chỉ một khoảng đất quét sạch gần đống lửa nhỏ chập chờn. Hắn chẳng thấy gì lạ khi một công chúa nằm trên đất trần cạnh lửa trại, quấn trong áo choàng của chiến binh.</> - Black Colossus\r\n\r\nLửa trại là bạn thân nhất của nhà thám hiểm khi đêm trở lạnh và bóng tối vây quanh. Làm từ cành và que đơn giản, lửa trại là nguồn sáng và hơi ấm tuyệt vời.\r\n\r\nLửa trại dùng để nướng thịt, điều quan trọng vì thú hoang ở Vùng Đất Lưu Đày nhiễm đủ loại ký sinh trùng. Thà ăn thịt cháy còn hơn bị ngộ độc nhiều ngày.\r\n\r\nTuy nhiên, có ánh lửa trại là có thể bị nhìn thấy. Lữ khách cẩn trọng nên giấu lửa, kẻo bị kẻ xấu phục kích trong đêm.",
}
def tr_para(p):
    key = p.strip()
    for rx, k in NORM:
        if rx.match(key): return P[k]
    if key.startswith("In large Shemitish cities such as"):
        return GUARD["uniforms such as these"] if "uniforms" in key else GUARD["weapons such as these"]
    # 'covetousnessby' typo variants handled by NORM; joined foundation paragraphs:
    if key.startswith("Foundations should be the starting point") and "Placing a foundation" in key:
        return P["Foundations should be the starting point for almost any structure. They provide stability to anything built atop them and prevent the growth of plants beneath them."] + " " + P["Placing a foundation is a significant act in the Exiled Lands. Once a foundation is placed by a clan or individual, that land is considered their territory. Nobody else may build in the immediate area, unless the foundation is destroyed."]
    return P.get(key)
def tr_text(t):
    sep = "\r\n\r\n" if "\r\n\r\n" in t else "\n\n"
    parts = t.split(sep); out = []
    for p in parts:
        lead = p[:len(p) - len(p.lstrip())]; trail = p[len(p.rstrip()):]
        if not p.strip(): out.append(p); continue
        v = tr_para(p)
        if v is None: return None
        out.append(lead + v + trail)
    return sep.join(out)
uniq = {}
for line in open(S + r"\dlc_unique.txt", encoding="utf-8"):
    i, rep = line.rstrip("\n").split("\t", 1); uniq[int(i)] = ast.literal_eval(rep)
vi = {}; miss = []
for i in range(580, 634):
    en = uniq[i]
    v = WHOLE.get(i) or tr_text(en)
    if v: vi[en] = v
    else: miss.append(i)
json.dump(vi, open(S + r"\dlc_vi_4.json", "w", encoding="utf-8"), ensure_ascii=False, indent=0)
print("translated", len(vi), "missing", miss)
